### PR TITLE
Add static resources for login and home.

### PR DESCRIPTION
**Pull request by JangYoungWhan**
Unfortunately, I didn't have time to implement test code for unit test, but I'll add it later.
So plz let me in.

### CODE REVIEW

**Comment by leadbrain** [comment]
Sorry, We need integration test at least.
We have a lot of time. Isn't it?

**Comment by JangYoungWhan** [comment]
Okay, I need to find better ways about to test redirection on home layout. And then, I ask you to pull request again.

**Comment by leadbrain** [comment]
Okey. 
But, I have plan about static routing like this.
https://www.jayway.com/2014/09/08/combining-a-site-and-api-in-compojure/
Please modify to separate static route and rest API.

**Comment by JangYoungWhan** [comment]
It seems like a good idea. I agree with this issue. However, I'll need time to consider ways you suggested.

**Pull request merged**
